### ISSUE TITLE
Admin Console currently needs python3-pip & python3-jinja2

### ISSUE THREAD

**Issue by holta** [iiab/iiab-admin-console#527]
Question for @tim-moody:

Can Admin Console install these 2 apt package prereqs / dependencies?

For now these 2 installs are taken care of at the end of [9-local-addons/tasks/main.yml](https://github.com/iiab/iiab/blob/e832ec6635ada95c4bd9bcd63645b64315af4327/roles/9-local-addons/tasks/main.yml#L45-L51) here:

```
- name: "INSTALL python3-pip FOR ADMIN CONSOLE 'cmdsrv : Download speedtest-cli' SEE PR #3494 -- INSTALL python3-jinja2 FOR ADMIN CONSOLE 'js-menu : Post process the downloaded menu defs' SEE PR #3496 -- REMOVE THIS CODE LATER"
  package:
    name:
      - python3-pip
      - python3-jinja2
    state: present
  when: admin_console_install
```

Background:

- PR iiab/iiab#3494
- PR iiab/iiab#3496
